name: Build and Release Speed Test App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller coverage

      - name: Run Unit Tests and Generate Coverage
        run: |
          coverage run -m unittest discover
          coverage report -m

      - name: Build Executable
        run: |
          pyinstaller --onefile src/speedtest_app.py

      - name: Upload Executable to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/speedtest_app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
