name: CI/CD Pipeline

on:
  push:
    branches:
      - main  #Trigger pipeline on commits to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      #Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      #Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #Step 4: Run tests automatically
      - name: Run Tests
        run: |
          coverage run -m unittest discover
          coverage report -m

      #Step 5: Deploy the application
      - name: Deploy Application
        run: |
          echo "Packaging the Python script..."
          mkdir -p dist
          cp src/app.py dist/
          echo "Deployment complete. Packaged script is in the 'dist' folder."

      #Step 6: Upload the packaged script as an artifact
      - name: Upload Packaged Script
        uses: actions/upload-artifact@v4
        with:
          name: packaged-script
          path: dist/

      #Step 7: Notify Success 
      - name: Notify Success
        if: success()
        run: |
          echo "CI/CD pipeline completed successfully!"